---

- name: Infrastructure deployment
  gather_facts: false
  hosts: localhost
  connection: local
  tasks:

    - name: Execute terraform apply
      terraform:
        project_path: '../terraform'
        state: present
        force_init: True
      register: terraform_output

    - name: Print terrform outputs
      debug:
        msg: "{{ terraform_output.outputs }}"

    - name: Get ssh private key content
      copy:
        content: "{{ terraform_output.outputs.ssh_private_key.value }}"
        dest: "{{ lookup('env', 'PWD') }}/ssh/default.pem"
        mode: 0600

    - name: Ensure SSH key permissions
      file:
        path: "{{ lookup('env', 'PWD') }}/ssh/default.pem"
        mode: 0600

    - meta: refresh_inventory

- name: Ensure that hosts are running
  gather_facts: False
  hosts: jenkins
  become: False
  tasks:
      
  - name: Wait for system to become reachable
    wait_for_connection:
      delay: 10
      timeout: 300
      
- import_playbook: 01-filesystems.yml
#- import_playbook: 02-docker-setup.yml
#- import_playbook: 03-jenkins-setup.yml
