---

- name: Jenkins server setup
  gather_facts: True
  hosts: jenkins
  become: True

  roles:

    - role: ansible-role-jenkins-server
      jenkins_groups: [ "jenkins","docker" ]
      jenkins_plugins: [ "configuration-as-code","terraform" ]
